In [136]:
from matplotlib import pyplot as plt
import numpy as np

c=np.array([[2,1,3,0],[1,1,0,5],[3,3,1,0],[2,0,0,2]])
m=np.array([[1,0,2],[2,1,0],[1,0,3]])

In [12]:
def convolution(matrix, kernel):
    k_size = len(kernel)
    m_height, m_width = matrix.shape
    padded = np.pad(matrix, (k_size-1, k_size-1))
    
    output = []
    for i in range(m_height):
        for j in range(m_width):
            output.append(np.sum(padded[i:k_size+i, j:k_size+j]*kernel))

    output=np.array(output).reshape((m_height, m_width))
    return output

In [127]:
def convolve(matrix,kernel):
    
    kl = len(kernel)-1
    ks = (kl-1)//2 
    imx = len(matrix)-1
    imy = len(matrix[0])-1
    for i in range(imx):
        for j in range(imy):
            acc = 0
            for ki in range(kl): 
                for kj in range(kl):
                    if 0 <= i-ks <= kl: ## make sure you don't get out of bound error
                          acc = acc + (matrix[i-ks+ki][j-ks+kj] * kernel[ki][kj]) 
            matrix[i][j] = acc
        
    return matrix

In [13]:
convolution(c, m)

array([[ 6,  3, 11,  1],
       [ 3,  5,  6, 21],
       [13, 12, 17,  6],
       [ 8,  5, 12, 24]])

In [121]:
c.shape

(4, 4)

In [105]:
rotateArray(c)

array([[2, 0, 0, 2],
       [0, 1, 3, 3],
       [5, 0, 1, 1],
       [0, 3, 1, 2]])

In [147]:
def rotateMatrix(M):
    return M[:,::-1][::-1,:]#rotate matrix

In [149]:
rotateMatrix(c)

array([[2, 0, 0, 2],
       [0, 1, 3, 3],
       [5, 0, 1, 1],
       [0, 3, 1, 2]])

In [82]:
b=np.array([1,2,3,4])
b.T[::-1]

array([4, 3, 2, 1])

In [40]:
range(5,0,-1)

range(5, 0, -1)

In [126]:
convolve(c, m)

array([[183, 453, 489,   0],
       [ 14,  40,  90,   1],
       [  4,   1,   5,   3],
       [  2,   0,   0,   2]])